### ISSUE TITLE
求助：日志级别输出不稳定

### ISSUE THREAD

**Issue by rtczza** [donnie4w/tklog#11]
代码如下：
```
use colored::*;
use tklog::{LOG, MODE, fatal, error, warn, info, debug};

const PAM_LOG_FILE: &str = "test.log";

pub fn log_init() {
    let levelstr = "{level}".green(); //日志级别标识设置为绿色
    let timestr = "{time}".yellow(); // 时间属性标识设置为黄色
    let filestr = "{file}".red(); //文件属性标识设置为红色
    let messagestr = ":{message}".blue(); // 信息属性标识修改为蓝色
    let s = format!("{} {} {} {}\n", levelstr, timestr, filestr, messagestr);
    //设置日志格式
    LOG.set_formatter(s.as_str());
    // 日志写入到文件
    LOG.set_cutmode_by_time(PAM_LOG_FILE, MODE::MONTH, 0, false);
    LOG.set_level(tklog::LEVEL::Debug);
}

fn main() {
    log_init();

    info!("info info info");
    debug!("debug debug debug");
    warn!("warn warn warn");
    error!("error error error");
    fatal!("fatal fatal fatal");
}

```

日志输出的级别，飘忽不定。运行如下所示，其中17行`LOG.set_level(tklog::LEVEL::Debug);` 对日志输出，无影响。
![image](https://github.com/user-attachments/assets/c294121f-5819-4a32-9c9a-4c927c40f9f7)

同样写到文件的内容也有丢失，红色箭头标注出来了，如下所示：
![image](https://github.com/user-attachments/assets/3bc0d67e-b30c-428a-9356-dabd6bb9cad6)

是初始化设置有问题，还是接口调用不当？tklog是否支持RUST_LOG环境变量？期待大佬回复。

**Comment by donnie4w** [comment]
@rtczza  
tklog默认模式下，写日志是的模式是  `tklog::PRINTMODE::DELAY` ，这个模式会比较快，但是日志会先写入通道。
你的测试日志写入后马上退出了，可能导致部分日志数据未写入文件就退出了。
你可以修改这个模式调用  LOG.set_printmode(tklog::PRINTMODE::PUNCTUAL);  这个模式会同步写入日志。

再测试可以改用下面两种方式
一. 是 加一个时间暂停，不马上退出
```rust
fn logtest() {
    log_init();
    info!("info info info");
    debug!("debug debug debug");
    warn!("warn warn warn");
    error!("error error error");
    fatal!("fatal fatal fatal");
    thread::sleep(Duration::from_secs(1));
}
```

二. 是设置 set_printmode 为 tklog::PRINTMODE::PUNCTUAL
`LOG.set_printmode(tklog::PRINTMODE::PUNCTUAL);`

-------

tklog暂时未支持RUST_LOG，下个版本会增加

**Comment by rtczza** [comment]
感谢大佬回复。

我这边测试，使用`LOG.set_printmode(tklog::PRINTMODE::PUNCTUAL);` 可以满足要求了。（因为项目中使用日志记录较多，所以尽量不使用延时机制了）。大佬，有测试过开启同步写入日志，对性能的影响吗？没有需求，就是突然想到问一下。

期待下一个版本的发布！

**Comment by donnie4w** [comment]
@rtczza 
解释一下，可能是变量命名导致误解，`tklog::PRINTMODE::DELAY` 的实际作用并不是延时，准确一点说应该是异步，但是与async机制的异步有一些区别，async时乱序的，而DELAY可以保证日志的有序性，只是写数据是在另一个线程中进行。DELAY不但不是延时，相反，它理论上应该更及时, 也就是它总体写数据时间更短，所以效率更高。
不过，如果你程序严格要求写日志与其他的业务逻辑代码的执行同步，则需要 使用 `tklog::PRINTMODE::PUNCTUAL` 

--------

两种机制在性能上有一些差异，特别时在Linux环境中。

总的来说：设置为`tklog::PRINTMODE::PUNCTUAL`时tklog的性能与 `log4rs` 与 `tracing` 相差不大

这里有一个Linux虚拟机环境的测试数据，可以参考

**测试环境为 Ubuntu 24.04.1 LTS**


#### 设置为 **tklog::PRINTMODE::PUNCTUAL**  的测试数据

![](https://tlnet.top/f/1730107084_2724.jpg)



#### 设置为 **tklog::PRINTMODE::DELAY**   的测试数据

![](https://tlnet.top/f/1730107090_3484.jpg)


#### 可以看到，在Linux虚拟机中，

- PUNCTUAL机制 时，3个库的数据都在150微秒左右
- DELAY机制时，tklog效率提升到 800 纳秒左右

#### 也就是说，在linux环境中 ， 默认使用 **tklog::PRINTMODE::DELAY** 时，tklog的性能是tracing或log4rs的10倍以上，如果 设置为 **tklog::PRINTMODE::PUNCTUAL**  时，则性能与 tracing或log4rs 相当(**注意，结论是基于基准测试数据，不同环境结论可能不同**)


在windows环境中，差距比较小，大概为两倍左右，可以参考该文章 [《Rust日志库性能压测 — log4rs + tracing + tklog》](https://tlnet.top/article/22425193)

**Comment by rtczza** [comment]
感谢大佬专业、详细的说明回复。太给力了。

我们现在已经在两个项目中用上tklog了，也会把项目推荐其他人。希望越来越多的人可以用上这么优秀的日志库。
